package projektor;

import cpw.mods.fml.common.ModMetadata;
import java.util.Arrays;
import net.minecraft.util.ResourceLocation;

public class Reference
{
    public static final class MetaData
    {
        /**
         * Setup mod metadata
         *
         * @param metadata
         * @return edited metadata object
         */
        public static ModMetadata init(ModMetadata metadata)
        {
            metadata.modId = Reference.Naming.ID;
            metadata.name = Reference.Naming.NAME;
            metadata.description = Reference.Naming.NAME + " is an extendable utility to place non-solid 'ghost' blocks in the world";
            metadata.url = "https://github.com/jakimfett/Projektor";
            metadata.logoFile = "assets/" + Reference.Naming.ID + "/logo.png";
            metadata.version = Reference.Versioning.V_MAJOR + "." + Reference.Versioning.V_MINOR + "." + Reference.Versioning.V_REVIS;
            metadata.authorList = Arrays.asList("jakimfett", "hilburn", "way2muchnoise");
            metadata.autogenerated = false;
            return metadata;
        }
    }

    public static final class Naming
    {
        // Mod ID
        public static final String ID = "projektor";
        // Mod Name
        public static final String NAME = "Projektor";

        // BASE IDs
        public static final String PROJECTOR = "projector";

        public static final String SCHEMATIC_DEFAULT = "schematic";
    }

    public static final class Versioning
    {

        // Main version information that will be displayed in mod listing and for other purposes.
        public static final String V_MAJOR = "@MAJOR@";
        public static final String V_MINOR = "@MINOR@";
        public static final String V_REVIS = "@REVIS@";
        public static final String V_BUILD = "@BUILD@";
        public static final String VERSION_FULL = V_MAJOR + "." + V_MINOR + "." + V_REVIS + "." + V_BUILD;
    }

    public static final class Model
    {
        private static final String MODEL_DIR = "textures/model/";

        public static final ResourceLocation PROJECTOR_OFF = new ResourceLocation(Reference.Naming.ID, Reference.Model.MODEL_DIR + "ProjectorModelOn.png");
        public static final ResourceLocation PROJECTOR_ON = new ResourceLocation(Reference.Naming.ID, Reference.Model.MODEL_DIR + "ProjectorModelOff.png");
    }

    public static final class IIcon
    {
        private static final String PREFIX = Reference.Naming.ID + ":";
        public static final String DUMMY = PREFIX + "dummyBlockIcon";
    }

    public static final class Colors
    {

        public static final String Black = "\u00A70";
        public static final String DarkBlue = "\u00A71";
        public static final String DarkGreen = "\u00A72";
        public static final String DarkCyan = "\u00A73";
        public static final String DarkRed = "\u00A74";
        public static final String Purple = "\u00A75";
        public static final String Orange = "\u00A76";
        public static final String LightGrey = "\u00A77";
        public static final String DarkGrey = "\u00A78";
        public static final String LightBlue = "\u00A79";
        public static final String LightGreen = "\u00A7a";
        public static final String LightCyan = "\u00A7b";
        public static final String LightRed = "\u00A7c";
        public static final String Pink = "\u00A7d";
        public static final String Yellow = "\u00A7e";
        public static final String White = "\u00A7f";

    }

}
