package projektor.reference;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class MetaData
{
    /**
     * Setup mod metadata
     *
     * @param metadata
     * @return edited metadata object
     */
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = Reference.NAME + " is a mod that adds a projector to project builds in ghost blocks";
        metadata.url = "https://github.com/jakimfett/Projektor";
        //metadata.logoFile = "assets/" + Reference.ID + "/logo.png"; TODO: make logo
        metadata.version = Reference.V_MAJOR + "." + Reference.V_MINOR + "." + Reference.V_REVIS;
        metadata.authorList = Arrays.asList("jakimfett", "hilburn", "way2muchnoise");
        metadata.autogenerated = false;
        return metadata;
    }
}
