package projektor.reference;

import cpw.mods.fml.common.ModMetadata;
import java.util.Arrays;

public class MetaData
{
    /**
     * Setup mod metadata
     *
     * @param metadata
     * @return edited metadata object
     */
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Naming.ID;
        metadata.name = Naming.NAME;
        metadata.description = Naming.NAME + " is a mod that adds a projector to project builds in ghost blocks";
        metadata.url = "https://github.com/jakimfett/Projektor";
        metadata.logoFile = "assets/" + Naming.ID + "/logo.png";
        metadata.version = Naming.V_MAJOR + "." + Naming.V_MINOR + "." + Naming.V_REVIS;
        metadata.authorList = Arrays.asList("jakimfett", "hilburn", "way2muchnoise");
        metadata.autogenerated = false;
        return metadata;
    }
}
